# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'node_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12node_service.proto\"\x07\n\x05\x45mpty\";\n\x06Tensor\x12\x13\n\x0btensor_data\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t\"\'\n\x11\x43heckpointRequest\x12\x12\n\nmodel_file\x18\x01 \x01(\x0c\"\"\n\x0cModelRequest\x12\x12\n\nmodel_file\x18\x01 \x01(\x0c\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8e\x01\n\x0bNodeService\x12$\n\tSendModel\x12\r.ModelRequest\x1a\x06.Empty\"\x00\x12/\n\x0eSendCheckpoint\x12\x12.CheckpointRequest\x1a\x07.Tensor\"\x00\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_TENSOR']._serialized_start=31
  _globals['_TENSOR']._serialized_end=90
  _globals['_CHECKPOINTREQUEST']._serialized_start=92
  _globals['_CHECKPOINTREQUEST']._serialized_end=131
  _globals['_MODELREQUEST']._serialized_start=133
  _globals['_MODELREQUEST']._serialized_end=167
  _globals['_HELLOREQUEST']._serialized_start=169
  _globals['_HELLOREQUEST']._serialized_end=197
  _globals['_HELLOREPLY']._serialized_start=199
  _globals['_HELLOREPLY']._serialized_end=228
  _globals['_NODESERVICE']._serialized_start=231
  _globals['_NODESERVICE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
