# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12node_service.proto\"\x07\n\x05\x45mpty\";\n\x06Tensor\x12\x13\n\x0btensor_data\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t\"\'\n\x11\x43heckpointRequest\x12\x12\n\nmodel_file\x18\x01 \x01(\x0c\"\"\n\x0cModelRequest\x12\x12\n\nmodel_file\x18\x01 \x01(\x0c\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8e\x01\n\x0bNodeService\x12$\n\tSendModel\x12\r.ModelRequest\x1a\x06.Empty\"\x00\x12/\n\x0eSendCheckpoint\x12\x12.CheckpointRequest\x1a\x07.Tensor\"\x00\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_TENSOR = DESCRIPTOR.message_types_by_name['Tensor']
_CHECKPOINTREQUEST = DESCRIPTOR.message_types_by_name['CheckpointRequest']
_MODELREQUEST = DESCRIPTOR.message_types_by_name['ModelRequest']
_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'node_service_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Tensor = _reflection.GeneratedProtocolMessageType('Tensor', (_message.Message,), {
  'DESCRIPTOR' : _TENSOR,
  '__module__' : 'node_service_pb2'
  # @@protoc_insertion_point(class_scope:Tensor)
  })
_sym_db.RegisterMessage(Tensor)

CheckpointRequest = _reflection.GeneratedProtocolMessageType('CheckpointRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKPOINTREQUEST,
  '__module__' : 'node_service_pb2'
  # @@protoc_insertion_point(class_scope:CheckpointRequest)
  })
_sym_db.RegisterMessage(CheckpointRequest)

ModelRequest = _reflection.GeneratedProtocolMessageType('ModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELREQUEST,
  '__module__' : 'node_service_pb2'
  # @@protoc_insertion_point(class_scope:ModelRequest)
  })
_sym_db.RegisterMessage(ModelRequest)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'node_service_pb2'
  # @@protoc_insertion_point(class_scope:HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'node_service_pb2'
  # @@protoc_insertion_point(class_scope:HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

_NODESERVICE = DESCRIPTOR.services_by_name['NodeService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=22
  _EMPTY._serialized_end=29
  _TENSOR._serialized_start=31
  _TENSOR._serialized_end=90
  _CHECKPOINTREQUEST._serialized_start=92
  _CHECKPOINTREQUEST._serialized_end=131
  _MODELREQUEST._serialized_start=133
  _MODELREQUEST._serialized_end=167
  _HELLOREQUEST._serialized_start=169
  _HELLOREQUEST._serialized_end=197
  _HELLOREPLY._serialized_start=199
  _HELLOREPLY._serialized_end=228
  _NODESERVICE._serialized_start=231
  _NODESERVICE._serialized_end=373
# @@protoc_insertion_point(module_scope)
